<a href="https://colab.research.google.com/github/Bonkerzz2603/TH_deaplear_tuan1/blob/main/ThucHanhDeepLearn_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#NUMPY ARRAY
lst = [1,3,45,22]
print('python list : ',lst)
#lst sang numpy arr
np_lst = np.array(lst)
print('numpy array : ',np_lst)
#2d array
a = np.array([1,3,45,22])
print(a)

python list :  [1, 3, 45, 22]
numpy array :  [ 1  3 45 22]
[ 1  3 45 22]


In [2]:
#2 array 2 chieu
import numpy as np
c = np.array([[1,2,3],[4,5,6]])
print(c)
#hinh dang cua list (so cot, so dong)
print(c.shape)
#kieu du lieu
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [3]:
#array 3 chieu
import numpy as np
d = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])
print(d)
#hinh dang cua list (sophan tu, so cot, so dong)
print(c.shape)
#kieu du lieu
print(c.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 3)
int64


In [5]:
#array voi gia tri ban dau la 0- or 1
e= np.zeros((2,2))
f= np.ones((3,3))

print('zero matrix:\n ',e)
print('one matrix:\n ',f)

zero matrix:
  [[0. 0.]
 [0. 0.]]
one matrix:
  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#reshape va flatten

import numpy as np
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
#re shape lai thanh 3 cot 2 hang
f = e.reshape(3,2)
print(f)
print(f.shape)

print('\n')

g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])

print(g)
print(g.shape)
#re shape lai thanh 3 cot 4 hang
h = g.reshape(3,4)
print(h)
print(h.shape)

#re shape lai thanh 3 phantu 2 cot 2 hang
j = g.reshape(3,2,2)
print('re shape lai thanh 3 phantu 2 cot 2 hang\n',j)
print(j.shape)

#re shape lai thanh 2 phantu 3 cot 2 hang
k = g.reshape(2,3,2)
print('re shape lai thanh 2 phantu 3 cot 2 hang\n',k)
print(k.shape)






[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
(3, 4)
re shape lai thanh 3 phantu 2 cot 2 hang
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
(3, 2, 2)
re shape lai thanh 2 phantu 3 cot 2 hang
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
(2, 3, 2)


In [19]:
#platten
import numpy as np
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
#re shape lai thanh 3 cot 2 hang
f = e.flatten()
print(f)


print('\n')

g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])
#re shape lai thanh 3 cot 2 hang
j =g.flatten()
print(j)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[1. 2. 3. 4. 5. 6.]


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [22]:
#them dl voi hstack vaf vstack

f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])

h_stack = np.hstack((f,g))
print('noi chieu ngang(cot)\n',h_stack)

v_stack = np.vstack((f,g))
print('noi chieu doc(hang)\n',v_stack)

noi chieu ngang(cot)
 [1. 2. 3. 4. 5. 6.]
noi chieu doc(hang)
 [[1. 2. 3.]
 [4. 5. 6.]]


In [26]:
#sinh mang rand

a= np.random.randint(100, size=(5,))#5 phan tu mang 1  chieu
print('mang 1 chieu random',a)
b= np.random.randint(100, size=(3,4))# 3 cot 4 hang
print('mang 2 chieu random',b)
c= np.random.randint(100, size=(3,4,3))#3phantu(matrix) 4 cot 3 hang
print('mang 3 chieu random',c)

mang 1 chieu random [41 51 95 79 35]
mang 2 chieu random [[30 14 26 34]
 [36 18 10 16]
 [52 76 22  4]]
mang 3 chieu random [[[74 60 20]
  [34 34 17]
  [53 31 79]
  [43 72 14]]

 [[40  2 58]
  [91 70 15]
  [93 25 31]
  [44 60 85]]

 [[46  8 33]
  [91 34  2]
  [59 68 55]
  [88 93  6]]]


In [ ]:
#sinh mang so thuc ngau nhien