<a href="https://colab.research.google.com/github/Bonkerzz2603/TH_deaplear_tuan1/blob/main/ThucHanhDeepLearn_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY ARRAY


In [1]:
import numpy as np
#NUMPY ARRAY
lst = [1,3,45,22]
print('python list : ',lst)
#lst sang numpy arr
np_lst = np.array(lst)
print('numpy array : ',np_lst)
#2d array
a = np.array([1,3,45,22])
print(a)

python list :  [1, 3, 45, 22]
numpy array :  [ 1  3 45 22]
[ 1  3 45 22]


## array 2 chieu


In [2]:
#2 array 2 chieu
import numpy as np
c = np.array([[1,2,3],[4,5,6]])
print(c)
#hinh dang cua list (so cot, so dong)
print(c.shape)
#kieu du lieu
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## array 3 chieu


In [3]:
#array 3 chieu
import numpy as np
d = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])
print(d)
#hinh dang cua list (sophan tu, so cot, so dong)
print(c.shape)
#kieu du lieu
print(c.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 3)
int64


## array voi gia tri ban dau la 0 hoac 1


In [5]:
#array voi gia tri ban dau la 0- or 1
e= np.zeros((2,2))
f= np.ones((3,3))

print('zero matrix:\n ',e)
print('one matrix:\n ',f)

zero matrix:
  [[0. 0.]
 [0. 0.]]
one matrix:
  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## reshape

In [17]:
#reshape va flatten

import numpy as np
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
#re shape lai thanh 3 cot 2 hang
f = e.reshape(3,2)
print(f)
print(f.shape)

print('\n')

g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])

print(g)
print(g.shape)
#re shape lai thanh 3 cot 4 hang
h = g.reshape(3,4)
print(h)
print(h.shape)

#re shape lai thanh 3 phantu 2 cot 2 hang
j = g.reshape(3,2,2)
print('re shape lai thanh 3 phantu 2 cot 2 hang\n',j)
print(j.shape)

#re shape lai thanh 2 phantu 3 cot 2 hang
k = g.reshape(2,3,2)
print('re shape lai thanh 2 phantu 3 cot 2 hang\n',k)
print(k.shape)






[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
(3, 4)
re shape lai thanh 3 phantu 2 cot 2 hang
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
(3, 2, 2)
re shape lai thanh 2 phantu 3 cot 2 hang
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
(2, 3, 2)


#flatten

In [19]:
#platten
import numpy as np
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
#re shape lai thanh 3 cot 2 hang
f = e.flatten()
print(f)


print('\n')

g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])
#re shape lai thanh 3 cot 2 hang
j =g.flatten()
print(j)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[1. 2. 3. 4. 5. 6.]


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## them du  lieu theo chieu nganh va doc

In [22]:
#them dl voi hstack vaf vstack

f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])

h_stack = np.hstack((f,g))
print('noi chieu ngang(cot)\n',h_stack)

v_stack = np.vstack((f,g))
print('noi chieu doc(hang)\n',v_stack)

noi chieu ngang(cot)
 [1. 2. 3. 4. 5. 6.]
noi chieu doc(hang)
 [[1. 2. 3.]
 [4. 5. 6.]]


# sinh mang voi gia tri ngau nhien

In [26]:
#sinh mang rand

a= np.random.randint(100, size=(5,))#5 phan tu mang 1  chieu
print('mang 1 chieu random',a)
b= np.random.randint(100, size=(3,4))# 3 cot 4 hang
print('mang 2 chieu random',b)
c= np.random.randint(100, size=(3,4,3))#3phantu(matrix) 4 cot 3 hang
print('mang 3 chieu random',c)

mang 1 chieu random [41 51 95 79 35]
mang 2 chieu random [[30 14 26 34]
 [36 18 10 16]
 [52 76 22  4]]
mang 3 chieu random [[[74 60 20]
  [34 34 17]
  [53 31 79]
  [43 72 14]]

 [[40  2 58]
  [91 70 15]
  [93 25 31]
  [44 60 85]]

 [[46  8 33]
  [91 34  2]
  [59 68 55]
  [88 93  6]]]


## sinh mang voi gia tri thuc ngau nhien

In [28]:
#sinh mang so thuc ngau nhien
a = np.random.rand(5)
print('mang 1 chieu random\n',a)
b= np.random.rand(3,4)
print('mang 2 chieu random\n',b)
b= np.random.rand(3,4,3)
print('mang 3 chieu random\n',b)

mang 1 chieu random
 [0.92623436 0.78032402 0.03201315 0.15161948 0.57371016]
mang 2 chieu random
 [[0.51645845 0.26950345 0.70300755 0.50356288]
 [0.72235788 0.48054833 0.89880543 0.23427801]
 [0.16008587 0.7633952  0.81770012 0.19541323]]
mang 3 chieu random
 [[[0.51449433 0.78904353 0.58397344]
  [0.90107323 0.45693137 0.50866667]
  [0.76371268 0.9624718  0.84860483]
  [0.65383066 0.74821744 0.60379034]]

 [[0.74907174 0.63638276 0.71820486]
  [0.5394753  0.70964582 0.68886436]
  [0.43320097 0.82760577 0.44705678]
  [0.29426094 0.73359135 0.52781731]]

 [[0.13065354 0.68201173 0.48630709]
  [0.82460937 0.05156775 0.23342202]
  [0.89485032 0.34878979 0.03225406]
  [0.42894695 0.76218097 0.11477587]]]


## sinh mang so thuc ngau nhien voi phan phoi Gaussian

In [29]:
#sinh mang so ngau nhien teho pp Gaussian
a = np.random.normal(5,0.5,10) #(gia tri trung tam, do lech, so pt)
print('mang 1 chieu random\n',a)


mang 1 chieu random
 [6.06846364 5.00265155 5.15095108 4.91713999 4.90989646 4.48682463
 4.72371584 5.74259169 4.20641733 4.69237609]


## sinh ngau nhien 1 gia tri tu mang cho trc



In [31]:
a =np.random.choice([3,5,7,9])
print(a)

b= np.random.choice([3,5,7,9], size=(3,5))
print(b)

9
[[3 5 7 5 7]
 [9 5 3 5 3]
 [5 7 9 3 5]]


## thay doi gia tri cua ma tran

In [33]:
a = np.matrix(np.ones((5,5)))
print('matran :\n',a)
np.array(a)[2]=2
print('thay doi gia tri dong 3 voi array\n',a)
np.asarray(a)[2]=2
print('thay doi gia tri cot 3 voi asarray\n',a)

matran :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
thay doi gia tri dong 3 voi array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
thay doi gia tri cot 3 voi asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## sinh day sao theo khoan cho trc


In [34]:
#(start, stop, step)
a = np.arange(1,20)
print(a)

b= np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


#index va slice

In [37]:
#slice
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('dong dau: ',a[0])
print('dong thu 2: ',a[1])
#indexing
print('cot dau: ',a[:,0])
print('cot thu 2: ',a[:,1])
print('hai gia tri dau tien cua dong thu 2:',a[1,:2])

[[1 2 3]
 [4 5 6]]
dong dau:  [1 2 3]
dong thu 2:  [4 5 6]
cot dau:  [1 4]
cot thu 2:  [2 5]
hai gia tri dau tien cua dong thu 2: [4 5]


##pandas

In [41]:
import pandas as pd

a = pd.Series([1.,2.,3.])
print(a)
print('gia tri dau tien: ',a[0])
b= pd.Series([1.,2.,3.], index=['a','b','c'])
print(b)
print('gia tri dau tien: ',b['a'])
#tao pandas series tu dictionary
calories = {"day1":420,"day2":380,"day3":390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
gia tri dau tien:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
gia tri dau tien:  1.0
day1    420
day2    380
day3    390
dtype: int64


## dataframe


In [44]:
#np to pandas
h = np.array([[1,2],[3,4]])
df_h = pd.DataFrame(h)
print(df_h)
#pandas to np
np_h = np.array(df_h)
print(np_h)

   0  1
0  1  2
1  3  4
[[1 2]
 [3 4]]


##dataframe mang 2 chieu

In [45]:
dic = {'name': ['John', 'Smith'], 'Age': ['23', '34']}
df = pd.DataFrame(dic)
print(df)

    name Age
0   John  23
1  Smith  34


In [46]:
r = np.random.randn(20,4)
df = pd.DataFrame(r, columns=['so1','so2','so3','so4'])
print(df.head())


        so1       so2       so3       so4
0 -0.377659 -2.416192 -1.764558  0.685191
1  1.358553 -0.521023 -0.309562 -0.822150
2 -1.154247 -0.594477 -0.073202 -0.924729
3 -0.327797  1.668311 -0.081615  0.329074
4 -0.366757  0.588289  0.961529 -3.381796


##slice dataframe

In [51]:
r= np.random.randn(20,4)
df = pd.DataFrame(r, columns=['so1','so2','so3','so4'])
print(df.head())
#chon1
print(df['so1'])
#chon nhieu cot
print('chon nhieu cot')
print(df[['so1','so2']])
#chon dong
print('chon dong',df[0:3])
#chon nhieu dong nhieu cot
print('chon nhieu dong nhieu cot')
print(df.iloc[:3, :2])

#xoa cot
df = df.drop(columns=['so1','so4'])
print(df)

        so1       so2       so3       so4
0 -0.276947 -0.930163  1.912804  1.255180
1  0.629388  0.489921  0.066231 -1.672566
2 -0.567477  0.975597 -2.355617 -0.867769
3  0.333621 -0.723921  0.056440 -2.751208
4 -1.949579  0.985325 -0.068566 -0.758111
0    -0.276947
1     0.629388
2    -0.567477
3     0.333621
4    -1.949579
5     0.826476
6    -0.918779
7    -0.847070
8     0.222615
9     0.952696
10   -0.086945
11   -1.153606
12   -0.839894
13    1.407888
14    0.990529
15    0.271311
16   -0.391174
17    1.496792
18    0.149324
19   -0.758682
Name: so1, dtype: float64
chon nhieu cot
         so1       so2
0  -0.276947 -0.930163
1   0.629388  0.489921
2  -0.567477  0.975597
3   0.333621 -0.723921
4  -1.949579  0.985325
5   0.826476 -0.134165
6  -0.918779  0.011170
7  -0.847070 -0.132358
8   0.222615  0.372239
9   0.952696 -0.214593
10 -0.086945 -0.895921
11 -1.153606  0.103260
12 -0.839894  0.067694
13  1.407888  0.723015
14  0.990529 -1.100879
15  0.271311 -0.401209
16 -0.391174  1.

## noi nhieu data frame

##Tensor


#tensor 0

In [57]:
import tensorflow as tf


rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9,tf.int16)
print(r1)
r1_float = tf.constant(1.12,tf.float32)
print(r1_float)
r1_string = tf.constant('hello',tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'hello', shape=(), dtype=string)


#tensor 1 chieu

In [84]:
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


#tensor 2 chieu

In [59]:
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]], tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


#tensor n chieu


In [60]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
   [[6, 3, 62, 63, 84],
   [5, 56, 47, 18, 29]]
  ])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[ 6  3 62 63 84]
  [ 5 56 47 18 29]]], shape=(2, 2, 5), dtype=int32)


#teosor 0

In [83]:
t_Zero = tf.zeros(10)
print(t_Zero)

t2_zero = tf.zeros([2,2])
print(t2_zero)

t3_zero = tf.zeros([3,3,3])
print(t3_zero)



tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


# fill tensor

In [65]:
tf_1 = tf.fill(3,10)
print(tf_1)

tf_2 = tf.fill([3,3],15)
print(tf_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[15 15 15]
 [15 15 15]
 [15 15 15]], shape=(3, 3), dtype=int32)


#tensor 1 chieu voi linspace

In [66]:
lin_tensor = tf.linspace(5.0,20.0,5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


#tensor 1 chieu voi range

In [69]:
range_tensor = tf.range(3.0,7.0,delta=0.5)
print(range_tensor)


range2_tensor = tf.range(3.0,delta=0.5)
print(range2_tensor)


tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


#rand tensor

In [76]:
from random import uniform
range_tensor = tf.random.normal([5])
print(range_tensor)

range2_tensor = tf.random.normal([3,3])
print(range2_tensor)

trucated_tensor = tf.random.truncated_normal([3,3])
print(trucated_tensor)

uniform_tensor = tf.random.uniform([3,3])
print(uniform_tensor)
print(tf.random.shuffle(uniform_tensor))

tf.Tensor([-0.5243167  -0.31434393 -0.22466455 -0.17429473  0.8292484 ], shape=(5,), dtype=float32)
tf.Tensor(
[[-1.6904364   0.00972769 -0.76550215]
 [-1.0838792   1.0825723  -0.6854859 ]
 [-1.1881877  -0.24632193 -0.5381061 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.809019    0.02197658  0.80099523]
 [ 1.4061636   0.1069986  -0.960085  ]
 [ 0.3373519  -1.4092757   0.84629303]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.04394531 0.8852048  0.8772024 ]
 [0.44996393 0.5648705  0.8513094 ]
 [0.05382168 0.87904704 0.01217711]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.04394531 0.8852048  0.8772024 ]
 [0.44996393 0.5648705  0.8513094 ]
 [0.05382168 0.87904704 0.01217711]], shape=(3, 3), dtype=float32)


#chuyen do kieu dl

In [77]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


#can bac 2 cua 1 tensor

In [78]:
x = tf.constant(2., dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


#cong 2 tensor

In [79]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.add(a, b)
d = a + b

print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


#nhan 2 tensor

In [ ]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.multiply(a, b)
d = a * b

print(c)
print(d)

#cac phep toan tensor


In [81]:

a = tf.constant([6., 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3., 3., 3.])

d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(d)
print(l)

tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


# cac phep lam tron

In [ ]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])

r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)

print(r4)

#cac phep tren vector va matrix

In [85]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])

t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])

t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
