<a href="https://colab.research.google.com/github/Bonkerzz2603/TH_deaplearn_tuan1/blob/main/ThucHanhDeepLearn_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY ARRAY


In [ ]:
import numpy as np
#NUMPY ARRAY
lst = [1,3,45,22]
print('python list : ',lst)
#lst sang numpy arr
np_lst = np.array(lst)
print('numpy array : ',np_lst)
#2d array
a = np.array([1,3,45,22])
print(a)

python list :  [1, 3, 45, 22]
numpy array :  [ 1  3 45 22]
[ 1  3 45 22]


## array 2 chieu


In [ ]:
#2 array 2 chieu
import numpy as np
c = np.array([[1,2,3],[4,5,6]])
print(c)
#hinh dang cua list (so cot, so dong)
print(c.shape)
#kieu du lieu
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## array 3 chieu


In [ ]:
#array 3 chieu
import numpy as np
d = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])
print(d)
#hinh dang cua list (sophan tu, so cot, so dong)
print(c.shape)
#kieu du lieu
print(c.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 3)
int64


## array voi gia tri ban dau la 0 hoac 1


In [ ]:
#array voi gia tri ban dau la 0- or 1
e= np.zeros((2,2))
f= np.ones((3,3))

print('zero matrix:\n ',e)
print('one matrix:\n ',f)

zero matrix:
  [[0. 0.]
 [0. 0.]]
one matrix:
  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## reshape

In [ ]:
#reshape va flatten

import numpy as np
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
#re shape lai thanh 3 cot 2 hang
f = e.reshape(3,2)
print(f)
print(f.shape)

print('\n')

g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])

print(g)
print(g.shape)
#re shape lai thanh 3 cot 4 hang
h = g.reshape(3,4)
print(h)
print(h.shape)

#re shape lai thanh 3 phantu 2 cot 2 hang
j = g.reshape(3,2,2)
print('re shape lai thanh 3 phantu 2 cot 2 hang\n',j)
print(j.shape)

#re shape lai thanh 2 phantu 3 cot 2 hang
k = g.reshape(2,3,2)
print('re shape lai thanh 2 phantu 3 cot 2 hang\n',k)
print(k.shape)






[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
(3, 4)
re shape lai thanh 3 phantu 2 cot 2 hang
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
(3, 2, 2)
re shape lai thanh 2 phantu 3 cot 2 hang
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
(2, 3, 2)


#flatten

In [ ]:
#platten
import numpy as np
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
#re shape lai thanh 3 cot 2 hang
f = e.flatten()
print(f)


print('\n')

g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]])
#re shape lai thanh 3 cot 2 hang
j =g.flatten()
print(j)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[1. 2. 3. 4. 5. 6.]


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## them du  lieu theo chieu nganh va doc

In [ ]:
#them dl voi hstack vaf vstack

f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])

h_stack = np.hstack((f,g))
print('noi chieu ngang(cot)\n',h_stack)

v_stack = np.vstack((f,g))
print('noi chieu doc(hang)\n',v_stack)

noi chieu ngang(cot)
 [1. 2. 3. 4. 5. 6.]
noi chieu doc(hang)
 [[1. 2. 3.]
 [4. 5. 6.]]


# sinh mang voi gia tri ngau nhien

In [ ]:
#sinh mang rand

a= np.random.randint(100, size=(5,))#5 phan tu mang 1  chieu
print('mang 1 chieu random',a)
b= np.random.randint(100, size=(3,4))# 3 cot 4 hang
print('mang 2 chieu random',b)
c= np.random.randint(100, size=(3,4,3))#3phantu(matrix) 4 cot 3 hang
print('mang 3 chieu random',c)

mang 1 chieu random [41 51 95 79 35]
mang 2 chieu random [[30 14 26 34]
 [36 18 10 16]
 [52 76 22  4]]
mang 3 chieu random [[[74 60 20]
  [34 34 17]
  [53 31 79]
  [43 72 14]]

 [[40  2 58]
  [91 70 15]
  [93 25 31]
  [44 60 85]]

 [[46  8 33]
  [91 34  2]
  [59 68 55]
  [88 93  6]]]


## sinh mang voi gia tri thuc ngau nhien

In [ ]:
#sinh mang so thuc ngau nhien
a = np.random.rand(5)
print('mang 1 chieu random\n',a)
b= np.random.rand(3,4)
print('mang 2 chieu random\n',b)
b= np.random.rand(3,4,3)
print('mang 3 chieu random\n',b)

mang 1 chieu random
 [0.92623436 0.78032402 0.03201315 0.15161948 0.57371016]
mang 2 chieu random
 [[0.51645845 0.26950345 0.70300755 0.50356288]
 [0.72235788 0.48054833 0.89880543 0.23427801]
 [0.16008587 0.7633952  0.81770012 0.19541323]]
mang 3 chieu random
 [[[0.51449433 0.78904353 0.58397344]
  [0.90107323 0.45693137 0.50866667]
  [0.76371268 0.9624718  0.84860483]
  [0.65383066 0.74821744 0.60379034]]

 [[0.74907174 0.63638276 0.71820486]
  [0.5394753  0.70964582 0.68886436]
  [0.43320097 0.82760577 0.44705678]
  [0.29426094 0.73359135 0.52781731]]

 [[0.13065354 0.68201173 0.48630709]
  [0.82460937 0.05156775 0.23342202]
  [0.89485032 0.34878979 0.03225406]
  [0.42894695 0.76218097 0.11477587]]]


## sinh mang so thuc ngau nhien voi phan phoi Gaussian

In [ ]:
#sinh mang so ngau nhien teho pp Gaussian
a = np.random.normal(5,0.5,10) #(gia tri trung tam, do lech, so pt)
print('mang 1 chieu random\n',a)


mang 1 chieu random
 [6.06846364 5.00265155 5.15095108 4.91713999 4.90989646 4.48682463
 4.72371584 5.74259169 4.20641733 4.69237609]


## sinh ngau nhien 1 gia tri tu mang cho trc



In [ ]:
a =np.random.choice([3,5,7,9])
print(a)

b= np.random.choice([3,5,7,9], size=(3,5))
print(b)

9
[[3 5 7 5 7]
 [9 5 3 5 3]
 [5 7 9 3 5]]


## thay doi gia tri cua ma tran

In [ ]:
a = np.matrix(np.ones((5,5)))
print('matran :\n',a)
np.array(a)[2]=2
print('thay doi gia tri dong 3 voi array\n',a)
np.asarray(a)[2]=2
print('thay doi gia tri cot 3 voi asarray\n',a)

matran :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
thay doi gia tri dong 3 voi array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
thay doi gia tri cot 3 voi asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## sinh day sao theo khoan cho trc


In [ ]:
#(start, stop, step)
a = np.arange(1,20)
print(a)

b= np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


#index va slice

In [ ]:
#slice
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('dong dau: ',a[0])
print('dong thu 2: ',a[1])
#indexing
print('cot dau: ',a[:,0])
print('cot thu 2: ',a[:,1])
print('hai gia tri dau tien cua dong thu 2:',a[1,:2])

[[1 2 3]
 [4 5 6]]
dong dau:  [1 2 3]
dong thu 2:  [4 5 6]
cot dau:  [1 4]
cot thu 2:  [2 5]
hai gia tri dau tien cua dong thu 2: [4 5]


##pandas

In [ ]:
import pandas as pd

a = pd.Series([1.,2.,3.])
print(a)
print('gia tri dau tien: ',a[0])
b= pd.Series([1.,2.,3.], index=['a','b','c'])
print(b)
print('gia tri dau tien: ',b['a'])
#tao pandas series tu dictionary
calories = {"day1":420,"day2":380,"day3":390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
gia tri dau tien:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
gia tri dau tien:  1.0
day1    420
day2    380
day3    390
dtype: int64


## dataframe


In [ ]:
#np to pandas
h = np.array([[1,2],[3,4]])
df_h = pd.DataFrame(h)
print(df_h)
#pandas to np
np_h = np.array(df_h)
print(np_h)

   0  1
0  1  2
1  3  4
[[1 2]
 [3 4]]


##dataframe mang 2 chieu

In [ ]:
dic = {'name': ['John', 'Smith'], 'Age': ['23', '34']}
df = pd.DataFrame(dic)
print(df)

    name Age
0   John  23
1  Smith  34


In [ ]:
r = np.random.randn(20,4)
df = pd.DataFrame(r, columns=['so1','so2','so3','so4'])
print(df.head())


        so1       so2       so3       so4
0 -0.377659 -2.416192 -1.764558  0.685191
1  1.358553 -0.521023 -0.309562 -0.822150
2 -1.154247 -0.594477 -0.073202 -0.924729
3 -0.327797  1.668311 -0.081615  0.329074
4 -0.366757  0.588289  0.961529 -3.381796


##slice dataframe

In [ ]:
r= np.random.randn(20,4)
df = pd.DataFrame(r, columns=['so1','so2','so3','so4'])
print(df.head())
#chon1
print(df['so1'])
#chon nhieu cot
print('chon nhieu cot')
print(df[['so1','so2']])
#chon dong
print('chon dong',df[0:3])
#chon nhieu dong nhieu cot
print('chon nhieu dong nhieu cot')
print(df.iloc[:3, :2])

#xoa cot
df = df.drop(columns=['so1','so4'])
print(df)

        so1       so2       so3       so4
0 -0.276947 -0.930163  1.912804  1.255180
1  0.629388  0.489921  0.066231 -1.672566
2 -0.567477  0.975597 -2.355617 -0.867769
3  0.333621 -0.723921  0.056440 -2.751208
4 -1.949579  0.985325 -0.068566 -0.758111
0    -0.276947
1     0.629388
2    -0.567477
3     0.333621
4    -1.949579
5     0.826476
6    -0.918779
7    -0.847070
8     0.222615
9     0.952696
10   -0.086945
11   -1.153606
12   -0.839894
13    1.407888
14    0.990529
15    0.271311
16   -0.391174
17    1.496792
18    0.149324
19   -0.758682
Name: so1, dtype: float64
chon nhieu cot
         so1       so2
0  -0.276947 -0.930163
1   0.629388  0.489921
2  -0.567477  0.975597
3   0.333621 -0.723921
4  -1.949579  0.985325
5   0.826476 -0.134165
6  -0.918779  0.011170
7  -0.847070 -0.132358
8   0.222615  0.372239
9   0.952696 -0.214593
10 -0.086945 -0.895921
11 -1.153606  0.103260
12 -0.839894  0.067694
13  1.407888  0.723015
14  0.990529 -1.100879
15  0.271311 -0.401209
16 -0.391174  1.

## noi nhieu data frame

##bai tap numpy & pandas

#bai 1

In [2]:
import numpy as np
arr = np.random.randint(0, 21, (3, 3))
print("Mảng:\n", arr)

print("Tất cả phần tử khác 0:", np.all(arr != 0))

Mảng:
 [[14  7  9]
 [18  3 14]
 [12  6 12]]
Tất cả phần tử khác 0: True


# bai 2

In [3]:
arr = np.random.randint(0, 21, (3, 3))
print("\nMảng:\n", arr)

print("Tồn tại phần tử khác 0:", np.any(arr != 0))


Mảng:
 [[10 12  3]
 [ 7 13  9]
 [20  5  9]]
Tồn tại phần tử khác 0: True


#bai3

In [4]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 1])

print("\nSo sánh mảng 1 chiều")
print("greater:", np.greater(a, b))
print("greater_equal:", np.greater_equal(a, b))
print("less:", np.less(a, b))
print("less_equal:", np.less_equal(a, b))

a2 = np.array([[1, 2], [3, 4]])
b2 = np.array([[2, 2], [1, 5]])

print("\nSo sánh mảng 2 chiều")
print("greater:\n", np.greater(a2, b2))
print("greater_equal:\n", np.greater_equal(a2, b2))
print("less:\n", np.less(a2, b2))
print("less_equal:\n", np.less_equal(a2, b2))


So sánh mảng 1 chiều
greater: [False False  True]
greater_equal: [False  True  True]
less: [ True False False]
less_equal: [ True  True False]

So sánh mảng 2 chiều
greater:
 [[False False]
 [ True False]]
greater_equal:
 [[False  True]
 [ True False]]
less:
 [[ True False]
 [False  True]]
less_equal:
 [[ True  True]
 [False  True]]


#bai4

In [5]:
arr = np.array([1]*10 + [0]*10 + [5]*10)
print("\nMảng:", arr)



Mảng: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]


#bai5

In [6]:
arr = np.arange(30, 71, 2)
print("\nCác số chẵn từ 30 đến 70:")
print(arr)



Các số chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#bai6

In [7]:
identity_matrix = np.identity(3)
print("\nMa trận đơn vị 3x3:")
print(identity_matrix)


Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#bai7

In [8]:
arr = np.arange(15, 56)
arr[1:-1] = 0

print("\nMảng sau khi đổi giá trị:")
print(arr)



Mảng sau khi đổi giá trị:
[15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 55]


#bai8

In [9]:
arr = np.random.randint(0, 21, 20)

print("\nMảng ban đầu:")
print(arr)

arr[(arr >= 9) & (arr <= 15)] *= -1

print("Mảng sau khi đổi dấu:")
print(arr)


Mảng ban đầu:
[16  7  4 14  2 14 11 20  2 20  5 10  9  9  5 20 15 20  8 17]
Mảng sau khi đổi dấu:
[ 16   7   4 -14   2 -14 -11  20   2  20   5 -10  -9  -9   5  20 -15  20
   8  17]


#bai9

In [10]:
matrix = np.random.randint(10, 22, (3, 4))

print("\nMa trận 3x4:")
print(matrix)



Ma trận 3x4:
[[17 16 15 16]
 [11 17 19 18]
 [17 21 11 13]]


#bai10

In [11]:
matrix = np.ones((10, 10), dtype=int)

matrix[1:-1, 1:-1] = 0

print("\nMa trận 10x10:")
print(matrix)



Ma trận 10x10:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#bai11

In [12]:
diag_matrix = np.diag([1, 2, 3, 4, 5])

print("\nMa trận đường chéo:")
print(diag_matrix)



Ma trận đường chéo:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#bai12

In [13]:
arr = np.random.randint(0, 10, (3, 3, 3))

print("\nMảng 3x3x3:")
print(arr)

print("Tổng theo dòng:")
print(np.sum(arr, axis=1))

print("Tổng theo cột:")
print(np.sum(arr, axis=2))


Mảng 3x3x3:
[[[9 4 9]
  [2 9 3]
  [1 6 7]]

 [[4 8 8]
  [1 6 9]
  [0 6 1]]

 [[8 8 3]
  [4 0 0]
  [0 2 5]]]
Tổng theo dòng:
[[12 19 19]
 [ 5 20 18]
 [12 10  8]]
Tổng theo cột:
[[22 14 14]
 [20 16  7]
 [19  4  7]]


#bai13

In [14]:
a = np.random.randint(1, 10, 10)
b = np.random.randint(1, 10, 10)

print("\nVector a:", a)
print("Vector b:", b)

print("Inner product:", np.dot(a, b))



Vector a: [4 1 8 2 2 3 7 6 3 1]
Vector b: [2 5 1 1 3 2 9 4 4 2]
Inner product: 136


#bai14

In [15]:
A = np.random.randint(1, 10, (4, 3))
y = np.random.randint(1, 10, 3)

print("\nMa trận A:")
print(A)

print("Vector y:")
print(y)

result = A + y

print("Kết quả:")
print(result)


Ma trận A:
[[9 3 5]
 [1 9 2]
 [2 6 9]
 [4 6 6]]
Vector y:
[4 8 7]
Kết quả:
[[13 11 12]
 [ 5 17  9]
 [ 6 14 16]
 [ 8 14 13]]


#bai15

In [16]:
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng:")
print(s1 + s2)

print("\nTrừ:")
print(s1 - s2)

print("\nNhân:")
print(s1 * s2)

print("\nChia:")
print(s1 / s2)


Cộng:
0     3
1     7
2    11
3    15
4    20
dtype: int64

Trừ:
0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhân:
0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


#bai16

In [17]:
df = pd.DataFrame({
    'col1': [1,2,3,4,7,11],
    'col2': [4,5,6,9,5,0],
    'col3': [7,5,8,12,1,11]
})

print(df)

series1 = df.iloc[:, 0]

print("\nCột đầu tiên dạng Series:")
print(series1)


   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

Cột đầu tiên dạng Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


#bai17

In [18]:
df = pd.DataFrame(np.random.randint(1, 100, (4, 3)),
                  columns=['A', 'B', 'C'])

print("\nDataFrame ban đầu:")
print(df)

sorted_df = df.sort_values(by='A')

print("\nDataFrame sau khi sắp xếp:")
print(sorted_df)



DataFrame ban đầu:
    A   B   C
0  59  17  59
1  45  31  37
2  91  89  13
3  30  18  34

DataFrame sau khi sắp xếp:
    A   B   C
3  30  18  34
1  45  31  37
0  59  17  59
2  91  89  13


#bai18

In [19]:
s = pd.Series([1,2,3,4,5], index=['A','B','C','D','E'])

print("\nSeries ban đầu:")
print(s)

new_s = s.reindex(['B','A','C','D','E'])

print("\nSeries sau khi đổi index:")
print(new_s)


Series ban đầu:
A    1
B    2
C    3
D    4
E    5
dtype: int64

Series sau khi đổi index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


#bai19

In [20]:
sr1 = pd.Series([1,2,3,4,5])
sr2 = pd.Series([2,4,6,8,10])

result = sr1[~sr1.isin(sr2)]

print("\nPhần tử của sr1 không có trong sr2:")
print(result)




Phần tử của sr1 không có trong sr2:
0    1
2    3
4    5
dtype: int64


#bai20

In [21]:
x = np.random.randint(0, 20, 20)
y = np.random.randint(0, 20, 20)

print("\nMảng x:")
print(x)

print("\nMảng y:")
print(y)

print("\nHợp:")
print(np.union1d(x, y))

print("\nGiao:")
print(np.intersect1d(x, y))



Mảng x:
[ 6 10  7  7  2  4 19  4 17  7 13  6 19  9 11  6 13 11 10  6]

Mảng y:
[13  1 11 17  9 17  8 18 14  0  8 11  4  0  1 10 16  7 11 15]

Hợp:
[ 0  1  2  4  6  7  8  9 10 11 13 14 15 16 17 18 19]

Giao:
[ 4  7  9 10 11 13 17]


#bai21

In [22]:
x = pd.Series(range(10))
y = pd.Series(list('pqrstuvwxy'))

print("\nSeries x:")
print(x)

print("\nSeries y:")
print(y)

vertical = pd.concat([x, y])

horizontal = pd.concat([x, y], axis=1)

print("\nGhép dọc:")
print(vertical)

print("\nGhép ngang:")
print(horizontal)



Series x:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

Series y:
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Ghép dọc:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Ghép ngang:
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


#bai22

In [24]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James',
             'Emily', 'Michael', 'Matthew', 'Laura',
             'Kevin', 'Jonas'],

    'score': [12.5, 9, 16.5, np.nan,
              9, 20, 14.5, np.nan,
              8, 19],

    'attempts': [1,3,2,3,2,3,1,1,2,1],

    'qualify': ['yes','no','yes','no',
                'no','yes','yes','no',
                'no','yes']
}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data, index=labels)

print("\nDataFrame:")
print(df)


# BÀI 23
print("\n3 dòng đầu tiên:")
print(df.head(3))


# BÀI 24
print("\nCột name và score:")
print(df[['name', 'score']])


# BÀI 25
print("\nDòng có attempts > 2:")
print(df[df['attempts'] > 2])


# BÀI 26
print("\nSố dòng, số cột:")
print(df.shape)

# BÀI 27
print("\nDòng có score là NaN:")
print(df[df['score'].isnull()])


# BÀI 28
print("\nDòng có score từ 15 đến 20:")
print(df[df['score'].between(15, 20)])


# BÀI 29
print("\nAttempts > 2 và score từ 15 đến 20:")
print(df[(df['attempts'] > 2) &
         (df['score'].between(15, 20))])


# BÀI 30
df.loc['d', 'score'] = 19

print("\nDataFrame sau khi cập nhật:")
print(df)


DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

3 dòng đầu tiên:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

Cột name và score:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

Dòng có attempts > 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3  

##Tensor


#tensor 0

In [27]:
import tensorflow as tf


rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9,tf.int16)
print(r1)
r1_float = tf.constant(1.12,tf.float32)
print(r1_float)
r1_string = tf.constant('hello',tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'hello', shape=(), dtype=string)


#tensor 1 chieu

In [28]:
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


#tensor 2 chieu

In [29]:
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]], tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


#tensor n chieu


In [30]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
   [[6, 3, 62, 63, 84],
   [5, 56, 47, 18, 29]]
  ])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[ 6  3 62 63 84]
  [ 5 56 47 18 29]]], shape=(2, 2, 5), dtype=int32)


#teosor 0

In [31]:
t_Zero = tf.zeros(10)
print(t_Zero)

t2_zero = tf.zeros([2,2])
print(t2_zero)

t3_zero = tf.zeros([3,3,3])
print(t3_zero)



tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


# fill tensor

In [32]:
tf_1 = tf.fill(3,10)
print(tf_1)

tf_2 = tf.fill([3,3],15)
print(tf_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[15 15 15]
 [15 15 15]
 [15 15 15]], shape=(3, 3), dtype=int32)


#tensor 1 chieu voi linspace

In [33]:
lin_tensor = tf.linspace(5.0,20.0,5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


#tensor 1 chieu voi range

In [34]:
range_tensor = tf.range(3.0,7.0,delta=0.5)
print(range_tensor)


range2_tensor = tf.range(3.0,delta=0.5)
print(range2_tensor)


tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


#rand tensor

In [35]:
from random import uniform
range_tensor = tf.random.normal([5])
print(range_tensor)

range2_tensor = tf.random.normal([3,3])
print(range2_tensor)

trucated_tensor = tf.random.truncated_normal([3,3])
print(trucated_tensor)

uniform_tensor = tf.random.uniform([3,3])
print(uniform_tensor)
print(tf.random.shuffle(uniform_tensor))

tf.Tensor([ 0.08645208 -0.35191777  0.5673759   0.73111033 -1.2718765 ], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.06427815  0.07269045  2.172139  ]
 [-1.1542387   0.263995    0.17304534]
 [ 0.00394158  0.02542955 -0.47764248]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.40130764  0.3978664  -0.04595375]
 [-1.1010929   0.929096   -1.1136378 ]
 [-1.3410954   1.5394518  -0.51368904]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.72267234 0.11384487 0.77050364]
 [0.730497   0.3819734  0.52909017]
 [0.14633429 0.63590956 0.75879955]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.72267234 0.11384487 0.77050364]
 [0.14633429 0.63590956 0.75879955]
 [0.730497   0.3819734  0.52909017]], shape=(3, 3), dtype=float32)


#chuyen do kieu dl

In [36]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


#can bac 2 cua 1 tensor

In [37]:
x = tf.constant(2., dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


#cong 2 tensor

In [38]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.add(a, b)
d = a + b

print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


#nhan 2 tensor

In [39]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.multiply(a, b)
d = a * b

print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


#cac phep toan tensor


In [40]:

a = tf.constant([6., 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3., 3., 3.])

d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(d)
print(l)

tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


# cac phep lam tron

In [41]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])

r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)

print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


#cac phep tren vector va matrix

In [42]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])

t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])

t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


##bai tap tensorflow

#bai1

In [43]:
t1 = tf.zeros([2, 3])
print("B1:\n", t1)

B1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


#bai2

In [44]:
X = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.zeros_like(X)
print("B2:\n", t2)

B2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


#bai3

In [45]:
t3 = tf.ones([3,2])
print("B3:\n", t3)

B3:
 tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#bai4

In [46]:
t4 = tf.range(6, 11, delta=2)  # [6, 8, 10]
print("B4:\n", t4)

B4:
 tf.Tensor([ 6  8 10], shape=(3,), dtype=int32)


#bai5

In [47]:
t5 = tf.range(10, 101, delta=2)
print("B5:\n", t5)

B5:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


#bai6

In [48]:
t6 = tf.random.normal([3,2], mean=0, stddev=2)
print("B6:\n", t6)

B6:
 tf.Tensor(
[[ 3.83063    -0.48505166]
 [-2.2430887  -4.105013  ]
 [ 0.80832094 -4.8237243 ]], shape=(3, 2), dtype=float32)


#bai7

In [49]:
t7 = tf.random.uniform([3,2], minval=0, maxval=2)
print("B7:\n", t7)

B7:
 tf.Tensor(
[[1.5172994 0.8294518]
 [1.6498153 1.5041218]
 [0.5436888 0.820745 ]], shape=(3, 2), dtype=float32)


#bai8

In [50]:
X = tf.constant([[1,2],[3,4],[5,6]])
t8 = tf.random.shuffle(X)
print("B8:\n", t8)

B8:
 tf.Tensor(
[[1 2]
 [5 6]
 [3 4]], shape=(3, 2), dtype=int32)


#bai9

In [51]:
t9 = tf.random.uniform([10,10,3])
t9_crop = tf.image.random_crop(t9, size=[5,5,3])
print("B9:\n", t9_crop.shape)

B9:
 (5, 5, 3)


#bai10

In [52]:
x = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)
y = tf.random.uniform([5], minval=0, maxval=10, dtype=tf.int32)

result = tf.where(x < y, x + y, x - y)
print("B10:")
print("x:", x.numpy())
print("y:", y.numpy())
print("result:", result.numpy())

B10:
x: [1 0 0 1 6]
y: [4 3 4 2 1]
result: [5 3 4 3 5]


#bai11

In [53]:
x = tf.random.uniform([3,2], minval=5, maxval=10, dtype=tf.int32)
y = tf.random.uniform([2,3], minval=15, maxval=20, dtype=tf.int32)

diag_x = tf.linalg.diag_part(x)
sum_xy = tf.matmul(x, y)

print("B11:")
print("x:\n", x.numpy())
print("y:\n", y.numpy())
print("diag x:", diag_x.numpy())
print("x + y (matmul):\n", sum_xy.numpy())

B11:
x:
 [[5 6]
 [5 7]
 [6 6]]
y:
 [[16 16 17]
 [18 18 19]]
diag x: [5 7]
x + y (matmul):
 [[188 188 199]
 [206 206 218]
 [204 204 216]]


#bai12

In [54]:
@tf.function
def tensor_ops(x, y):
    return x + y, x - y, x * y

x = tf.random.uniform([3,2,2])
y = tf.random.uniform([3,2,2])

add, sub, mul = tensor_ops(x, y)
print("B12:", add, sub, mul)


B12: tf.Tensor(
[[[0.8711562  0.6282648 ]
  [0.7888489  1.6088216 ]]

 [[1.5561112  0.68559957]
  [0.5581814  0.7942034 ]]

 [[0.8631896  0.8353689 ]
  [0.9482515  1.4150323 ]]], shape=(3, 2, 2), dtype=float32) tf.Tensor(
[[[-0.5119183  -0.27528155]
  [-0.7158301  -0.3784802 ]]

 [[ 0.31645238  0.58487725]
  [-0.09520042  0.67801464]]

 [[-0.8277544   0.48128223]
  [ 0.81451297  0.5089363 ]]], shape=(3, 2, 2), dtype=float32) tf.Tensor(
[[[0.1242132  0.07973418]
  [0.02746746 0.61126494]]

 [[0.580335   0.03199134]
  [0.07562584 0.0427638 ]]

 [[0.01497973 0.11655214]
  [0.05893737 0.43582505]]], shape=(3, 2, 2), dtype=float32)


#bai13

In [55]:
@tf.function
def sum_model(x, y):
    return tf.reduce_sum(x + y)

print("B13:", sum_model(x, y))

B13: tf.Tensor(11.55303, shape=(), dtype=float32)


#bai14

In [56]:
@tf.function
def diff_prod_model(x, y):
    return x - y, x * y

print("B14:", diff_prod_model(x, y))

B14: (<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[-0.5119183 , -0.27528155],
        [-0.7158301 , -0.3784802 ]],

       [[ 0.31645238,  0.58487725],
        [-0.09520042,  0.67801464]],

       [[-0.8277544 ,  0.48128223],
        [ 0.81451297,  0.5089363 ]]], dtype=float32)>, <tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0.1242132 , 0.07973418],
        [0.02746746, 0.61126494]],

       [[0.580335  , 0.03199134],
        [0.07562584, 0.0427638 ]],

       [[0.01497973, 0.11655214],
        [0.05893737, 0.43582505]]], dtype=float32)>)


#bai15,16

In [58]:
@tf.function
def perimeter(a, b):
    return (a + b) * 2

print("B15:", perimeter(5.0, 3.0))
@tf.function
def surface_area(a, b, c):
    Sxq = 2 * c * (a + b)
    Stp = 2 * (a*b + b*c + a*c)
    return Sxq, Stp

print("B16:", surface_area(2.0, 3.0, 4.0))

B15: tf.Tensor(16.0, shape=(), dtype=float32)
B16: (<tf.Tensor: shape=(), dtype=float32, numpy=40.0>, <tf.Tensor: shape=(), dtype=float32, numpy=52.0>)


#bai17,18

In [59]:
def is_parallelogram(AB, BC, CD, AD):
    return (AD == BC) and (AB == CD)

print("B17:", is_parallelogram(5,6,5,6))


# 18
def is_isosceles_trapezoid(AB, CD, AD, BC):
    return (AB == CD) == (AD == BC)

print("B18:", is_isosceles_trapezoid(5,5,6,6))

B17: True
B18: True


#bai19

In [60]:
# AM = MB, AN = NC => MN // BC và MN = BC/2

@tf.function
def midline(AM, MB, AN, NC, BC):
    condition = tf.logical_and(tf.equal(AM, MB), tf.equal(AN, NC))
    MN = BC / 2
    return condition, MN

cond, MN = midline(2.0,2.0,3.0,3.0,10.0)
print("B19:")
print("Điều kiện:", cond.numpy())
print("MN =", MN.numpy())

B19:
Điều kiện: True
MN = 5.0
